In [2]:
import torch
import pandas as pd
import numpy as np

import plotly.graph_objects as go
import plotly.express as px
import matplotlib.pyplot as plt

In [3]:
# setting device on GPU if available, else CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
print()

Using device: cuda



In [4]:
pd_dataframe = pd.read_csv("/home/kim/data/bedmap/bedmap123_preprocessed_DomeA.csv")

In [5]:
pd_dataframe.shape

(1786974, 8)

In [6]:
df = pd_dataframe[["x", "y", "b"]]
df = df[(df["x"] > 898750) & (df["x"] < 1498750) & (df["y"] > 250) & (df["y"] < 600250)]
df.shape

(1786974, 3)

In [7]:
mini = df[(df["x"] > 898750) & (df["x"] < (898750 + 200000)) & (df["y"] > 250) & (df["y"] < 250 + 200000)]

In [24]:
line = df[(df["x"] > 898750) & (df["x"] < (898750 + 200000)) & (df["y"] > 114000) & (df["y"] < 115000)]
line_shorter = df[(df["x"] > 1010000) & (df["x"] < (1040000)) & (df["y"] > 114350) & (df["y"] < 114700)]

## In 2D 

In [15]:
fig = go.Figure(data = go.Scatter(x = line["x"], y = line["b"], mode = 'markers'))
# Specify aspect ratio from data
fig.update_scenes(aspectmode = "data")
fig.show()

# Zoom in

In [30]:
tensor = torch.load("/home/kim/multimodal-superresolution/experiments/input_data_bedmachine/bedmachine_DOME_A.pt")

In [70]:
print(tensor[323, 6, 10, :])
# y is position 6 and we take 114500
# image 323, 324

tensor([114500., 114500., 114500., 114500., 114500., 114500., 114500., 114500.,
        114500., 114500., 114500., 114500., 114500., 114500., 114500., 114500.,
        114500., 114500., 114500., 114500., 114500., 114500., 114500., 114500.,
        114500., 114500., 114500., 114500., 114500., 114500., 114500., 114500.,
        114500., 114500., 114500., 114500., 114500., 114500., 114500., 114500.,
        114500., 114500., 114500., 114500., 114500., 114500., 114500., 114500.,
        114500., 114500., 114500., 114500., 114500., 114500., 114500., 114500.,
        114500., 114500., 114500., 114500.])


In [75]:
print(tensor[323, 7, 10, 42:60])

tensor([1010000., 1010500., 1011000., 1011500., 1012000., 1012500., 1013000.,
        1013500., 1014000., 1014500., 1015000., 1015500., 1016000., 1016500.,
        1017000., 1017500., 1018000., 1018500.])


In [79]:
print(tensor[324, 7, 10, 0:43])

tensor([1019000., 1019500., 1020000., 1020500., 1021000., 1021500., 1022000.,
        1022500., 1023000., 1023500., 1024000., 1024500., 1025000., 1025500.,
        1026000., 1026500., 1027000., 1027500., 1028000., 1028500., 1029000.,
        1029500., 1030000., 1030500., 1031000., 1031500., 1032000., 1032500.,
        1033000., 1033500., 1034000., 1034500., 1035000., 1035500., 1036000.,
        1036500., 1037000., 1037500., 1038000., 1038500., 1039000., 1039500.,
        1040000.])


In [77]:
print(tensor[324, 6, 10, 0:42])

tensor([114500., 114500., 114500., 114500., 114500., 114500., 114500., 114500.,
        114500., 114500., 114500., 114500., 114500., 114500., 114500., 114500.,
        114500., 114500., 114500., 114500., 114500., 114500., 114500., 114500.,
        114500., 114500., 114500., 114500., 114500., 114500., 114500., 114500.,
        114500., 114500., 114500., 114500., 114500., 114500., 114500., 114500.,
        114500., 114500.])


In [85]:
x_array = np.arange(start = 1010000, stop = 1040000 + 1, step = 500)

In [90]:
b_array = np.concatenate([np.array(tensor[323, 0, 10, 42:60]), tensor[324, 0, 10, 0:43]])

In [29]:
np.max(line_shorter["x"])-np.min(line_shorter["x"])
# over 30 km
# would be 60 grid cells

29488.86406638357

In [94]:
fig = go.Figure(data = go.Scatter(x = line_shorter["x"], y = line_shorter["b"], mode = 'markers'))
fig.add_trace(go.Scatter(x = x_array, y = b_array, mode = 'markers'))
# Specify aspect ratio from data
fig.update_scenes(aspectmode = "data")
fig.show()

fig = go.Figure(data = [go.Scatter3D(x = mini["x"], y = mini["y"], z = mini["b"],
                                   mode = 'markers')])
# Specify aspect ratio from data
fig.update_scenes(aspectmode = "data")
fig.show()